server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  application:
    name: ryver-auth
  datasource:
    url: jdbc:h2:file:./data/users;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE